spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Bookify
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54320}/${DB_NAME:bookify}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:admin}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration/general,classpath:db.migration/inserts
    schemas: public
logging:
  level:
    root: ${LOG_LEVEL:debug}
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: ${PKCS12_CERT_PASSWORD:cert}