spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Bookify
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54320}/${DB_NAME:bookify}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:admin}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: ${LOG_LEVEL:debug}