spring:
  datasource:
    username: test
    password: test
  flyway:
    locations: classpath:db.migration/general,classpath:db.migration/integration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: abc
            client-secret: abc